server:
  port: 8000
  address:

spring:
  application:
    name: serve-me
  datasource:
    url: jdbc:${CLEARDB_DATABASE_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    default-property-inclusion: NON_NULL
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT-5

mybatis:
  mapper-locations: classpath:mapper/*.xml

logging:
  level:
    root: info
#    edu.uta.cse.serveme.mapper: debug

pagehelper:
  helperDialect: mysql
  offsetAsPageNum: true
  pageSizeZero: true
  #    reasonable: true
  #    supportMethodsArguments: true
  rowBoundsWithCount: true

# custom defined params
user:
  role: USER
  group: User
  level: 0

jwt:
  secret: changeIt
  expire: 21600000
  delay: 60

cors:
  path: /**
  origins: http://localhost:8100,http://localhost:4200,http://localhost
  methods: GET,POST,PUT,DELETE,HEAD,OPTIONS
  headers: Content-Type,Authorization,credential,X-XSRF-TOKEN