server:
  port: 8000
  address:

spring:
  application:
    name: serve-me
  datasource:
    url: jdbc:${DB_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      username: ${DB_USER}
      password: ${DB_PASSWORD}
  jackson:
    default-property-inclusion: NON_NULL
#    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT-5
    serialization:
      fail-on-empty-beans: false
  jpa:
    hibernate:
      ddl-auto: update

logging:
  level:
    root: info
#    edu.uta.cse.serveme.mapper: debug

firebase:
  database: https://serve-me-ionic.firebaseio.com

# custom defined params
user:
  role: ROLE_USER,ROLE_CUSTOMER
  points: 0

cors:
  path: /**
  origins: http://localhost:8100,http://localhost:4200,http://localhost,capacitor://localhost,ionic://localhost
  methods: GET,POST,PUT,DELETE,HEAD,OPTIONS
  headers: Content-Type,Authorization,credential,X-XSRF-TOKEN