server:
  port: 8000
  address:

spring:
  application:
    name: serve-me
  datasource:
    url: jdbc:${CLEARDB_DATABASE_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      # default is 1800000
      max-lifetime: 180000
  jackson:
    default-property-inclusion: NON_NULL
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT-5
  jpa:
    hibernate:
      ddl-auto: update

logging:
  level:
    root: info
#    edu.uta.cse.serveme.mapper: debug

# custom defined params
user:
  role: USER
  level: 0

jwt:
  secret: changeIt
  expire: 21600000
  delay: 60

cors:
  path: /**
  origins: http://localhost:8100,http://localhost:4200,http://localhost,capacitor://localhost,ionic://localhost
  methods: GET,POST,PUT,DELETE,HEAD,OPTIONS
  headers: Content-Type,Authorization,credential,X-XSRF-TOKEN